import { NodePath } from "@babel/core";
import t, { FunctionDeclaration, ArrowFunctionExpression, FunctionExpression } from '@babel/types';
export declare const shouldIgnore: (path: NodePath) => t.Comment | undefined;
export declare const isTopFunction: (path: NodePath) => boolean;
export declare const getTopMostFunctionPath: (path: NodePath) => NodePath<t.Node> | null;
export declare const getParentFunctionPath: (path: NodePath) => NodePath<t.Node> | undefined;
export declare const isInFunction: (path: NodePath) => NodePath<t.Node> | null;
export declare const getTopPath: (path: NodePath) => NodePath<t.Program>;
export declare const getAllImport: (path: NodePath) => t.ImportDeclaration[];
export declare const hasTranslated: (path: NodePath, transFuncName: string) => boolean;
export declare const dealWithImport: (path: NodePath) => void;
export declare const shouldImport_transFunc_hook: (path: NodePath) => boolean;
export declare const shouldImport_transFunc_notHook: (path: NodePath) => boolean;
export declare const hasImported_transFunc: (path: NodePath, imported: string, source: string) => boolean;
export declare const checkAndImport_transFunc: (path: NodePath, imported: string, source: string) => void;
export declare const checkAndImport_transFunc_notHook: (path: NodePath) => void;
export declare const checkAndImport_transFunc_hook: (path: NodePath) => void;
export declare type TFunctionType = ArrowFunctionExpression | FunctionExpression | FunctionDeclaration;
export declare const getExposeHookNode: () => t.VariableDeclaration;
export declare const checkAndInsert_ExposeHook: (path: NodePath) => void;
export declare const hasInsert_ExposeHook: (path: NodePath) => boolean | t.Statement | undefined;
export declare const isReactFuncComp: (path: NodePath) => boolean | "" | undefined;
export declare const isCustomReactHookFunc: (path: NodePath) => boolean | "" | undefined;
export declare const isFunction: (path: NodePath) => boolean;
export declare const getKey: (keyMap: Record<string, string>, chinesesStr: string) => string | undefined;
export declare const writeFileIfNotExists: (directoryPath: string, fileName: string, content: string) => void;
