export const keyChineseMap = {
  "list.mytodo": "我的待办",
  "list.done": "操作记录",
  "list.today": "今日面试",
  "name": "姓名",
  "common.adress22aa": "22aa 地址aa",
  "common.name33aa": "33aa姓名 {{PageSize}}",
  "common.name44aa": "44aa姓名",
  "score.lowestExpression": "哦{{score}}分低于最低线",
  "score.o": "哦",
  "score.lowest": "分低于最低线",
  "score.olowest": "哦{{score}}分低于最低线",
  'inputAge1': '请输入你的年龄1',
  'inputAge2': '请输入你的年龄2',
  'inputAge3': '请输入你的年龄3',
  'inputAge4': '请输入你的年龄4',
  'inputAge5': '请输入你的年龄5：{{PageSize}}',
  'inputAge6': '请输入你的年龄6',
  'inputAge7': '请输入你的年龄7',
  'inputAge8': '请输入你的年龄8',
  '00Today': '00今日面试',
  '22aaTodayExpression': '请输入22aa今日面试:{{PageSize}}你的年龄8',
  'telephoneExpression': '电话1：{{PageSize}}:',
  'telephone': '电话2：',
  'Expression33TodayExpression': '{{param0}}33今日面试:{{param1}}',
}